version: '3.8'

services:
  pdb:
    image: postgres:14.5
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    environment:
      POSTGRES_DB: scheduler_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5678:5678"

  pgadmin:
    image: chorss/docker-pgadmin4
    ports:
      - "5050:5050"

volumes:
  db:
    driver: local
    #app:
    #driver: local
  pgadmin-data: